config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Redireciona usuários autenticados para posts#index
  authenticated :user do
    root to: "posts#index", as: :authenticated_root
  end

  # Redireciona visitantes não autenticados para home#index
  unauthenticated do
    root to: "home#index"
  end

  # CRUD routes for posts
  resources :posts
  get "my_posts", to: "posts#my_posts"

  # Add comments on posts
  resources :posts do
    resources :comments, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_presence_of :content
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title, :description
  has_one_attached :image
  has_many :comments, dependent: :destroy

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to @post, notice: "Comment added!"
    else
      redirect_to @post, alert: "Unable to add comment."
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [ :edit, :update, :destroy ]
  def index
    @posts = Post.all
  end

  def my_posts
    @posts = current_user.posts
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(posts_params)
    @post.user_id = current_user.id
    if @post.save!
      redirect_to my_posts_path, notice: "Post criado com sucesso"
    else
      redirect_to new_post_path, alert: "Erro ao criar o post, tente novamente"
    end
  end

  def edit
  end

  def update
    if @post.update(posts_params)
      redirect_to my_posts_path, notice: "Post editado com sucesso"
    else
      redirect_to edit_post_path, alert: "Erro ao editar o post, tente novamente"
    end
  end

  def destroy
    if @post.destroy
      redirect_to my_posts_path, notice: "Post excluído com sucesso"
    else
      redirect_to my_posts_path, alert: "Erro ao excluir o post, tente novamente"
    end
  end

  private
  def posts_params
    params.require(:post).permit(:title, :description)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment-wrapper">
  <p class="comment-content"><%= comment.content %></p>
  <p class="comment-author"><%= comment.user.email %></p>
</div>

app/views/home/index.html.erb
teste

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, media:"all", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", media:"all", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "home", media:"all", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <header>
      <%# Devise success and failure messages %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%# Devise signout button %>
      <%= button_to "Sign Out", destroy_user_session_path, :method => :delete , class: "button-secondary" if user_signed_in? %>
    </header>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model:post, html: { class: "form-wrapper" } do |form| %>
  <div class="form-item">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, value: post.title, placeholder:"Ex: Spring Break Details", class: "form-input" %>
  </div>

  <div class="form-item">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_field :description, value: post.description, placeholder:"My break was awesome! I went to...", class: "form-input" %>
  </div>

  <div class="form-item">
    <span class="form-label">Image (optional)</span>
    <%= form.label :image, class: "form-file-upload" %>
    <%= form.file_field :image %>
  </div>

  <%= form.submit "Save", class: "button" %>
<% end %>

app/views/posts/_post_template.html.erb
<div class="post-wrapper">
  <%= image_tag(post.image.attached? ? url_for(post.image) : image_path("fallback.png"), class: "post-image") %>

  <div class="post-header">
    <h2 class="post-title"><%= post.title %></h2>
    <nav class="post-nav">
      <% if post.user.id == current_user.id %>
        <%= link_to "Edit", edit_post_path(post), class: "button" %>
        <%= button_to "Delete", post, method: :delete, class: "button-secondary" %>
      <% end %>
    </nav>
  </div>
  
  <p class="post-content"><%= post.description %></p>
  <p class="post-author"> Author <%= post.user.email %></p>
  <p class="post-update"> Last update: <%= time_ago_in_words(post.updated_at) %></p>
  <hr/>

  <div class="comment-section-wrapper">
  <h4 class="post-comments-section-title">Comments</h4>
  <%= render post.comments %>
</div>


  <%= form_with model: [post, Comment.new], local: true, html: { class: "add-comment-wrapper" } do |form| %>
  <%= form.text_area :content, placeholder: "Add a comment...", class: "add-comment-content" %>
  <%= form.submit "Comment", class: "button" %>
<% end %>



</div>

app/views/posts/edit.html.erb
<div class="home-wrapper">
  <header class="home-header">
      <h1 class="home-title">Edit Post</h1>
      <nav class="home-nav">
        <%= link_to "Feed", posts_path, class: "button" %>
        <%= link_to "My Posts", my_posts_path, class: "button-secondary" %>

      </nav>
    </header>

<%= render partial: "posts/form", locals: {post: @post} %>
</div>

app/views/posts/index.html.erb
<div class="home-wrapper">
  <header class="home-header">
    <h1 class="home-title">Feed</h1>
    <nav class="home-nav">
      <%= link_to "My posts", my_posts_path, class: "button" %>
      <%= link_to "New Post", new_post_path, class: "button-secondary" %>

    </nav>
  </header>

  <section class="home-posts-wrapper">
    <% @posts.each do |post| %>
      <%= render partial: "posts/post_template", locals: {post: post} %>
    <% end %>
  </section>
</div>

app/views/posts/my_posts.html.erb
<div class="home-wrapper">
  <header class="home-header">
      <h1 class="home-title">My Posts</h1>
      <nav class="home-nav">
        <%= link_to "Feed", posts_path, class: "button" %>
        <%= link_to "New Post", new_post_path, class: "button-secondary" %>

      </nav>
    </header>

<section class="home-posts-wrapper">
    <% @posts.each do |post| %>
      <%= render partial: "posts/post_template", locals: {post: post} %>
    <% end %>
  </section>
</div>

app/views/posts/new.html.erb
<div class="home-wrapper">
  <header class="home-header">
      <h1 class="home-title">New Post</h1>
      <nav class="home-nav">
        <%= link_to "Feed", posts_path, class: "button" %>
        <%= link_to "My Posts", my_posts_path, class: "button-secondary" %>

      </nav>
    </header>

<section class="home-posts-wrapper">
    <%= render partial: "posts/form", locals: {post: @post} %>
  </section>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul class="error-list">
      <% resource.errors.full_messages.each do |message| %>
        <li class="error"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class:"link" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class:"link" %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class:"link" %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>